"""Extract kelimkar-relevant SQL from Supabase cluster backup."""
import re
from pathlib import Path

BACKUP = Path(r"c:\Users\kubik\Downloads\db_cluster-11-10-2025@01-04-25.backup (2)")
OUT = Path(__file__).resolve().parent / "kelimkar_restore.sql"

content = BACKUP.read_text(encoding="utf-8")


def extract_copy(schema: str, table: str):
    pat = rf"COPY {schema}\.{table} \(([^)]+)\) FROM stdin;\n(.*?)\n\\\."
    m = re.search(pat, content, re.DOTALL)
    if not m:
        return [], []
    cols = [c.strip().strip('"') for c in m.group(1).split(",")]
    rows = [ln for ln in m.group(2).strip().split("\n") if ln.strip()]
    return cols, rows


def pg_copy_field_to_sql(val: str, col: str) -> str:
    if val == r"\N":
        return "NULL"
    if col in ("raw_app_meta_data", "raw_user_meta_data", "identity_data"):
        escaped = val.replace("'", "''")
        return f"'{escaped}'::jsonb"
    escaped = val.replace("'", "''")
    return f"'{escaped}'"


def copy_row_to_insert(schema: str, table: str, cols: list[str], row: str) -> str:
    parts = row.split("\t")
    if len(parts) != len(cols):
        raise ValueError(f"{schema}.{table}: expected {len(cols)} cols, got {len(parts)}")
    values = []
    for col, part in zip(cols, parts):
        if part == r"\N":
            values.append("NULL")
        elif col in ("id", "user_id", "provider_id") and re.fullmatch(
            r"[0-9a-f-]{36}", part, re.I
        ):
            values.append(f"'{part}'::uuid")
        elif col in (
            "male_kelimky",
            "velke_kelimky",
            "id",
        ) and part.isdigit():
            values.append(part)
        elif col == "id" and table == "requests":
            values.append(part)
        elif col == "id" and table == "transactions":
            values.append(part)
        elif col in ("email_confirmed_at", "created_at", "updated_at", "last_sign_in_at",
                       "invited_at", "confirmation_sent_at", "recovery_sent_at",
                       "email_change_sent_at", "timestamp", "last_sign_in_at"):
            values.append(f"'{part}'::timestamptz" if "+" in part or " " in part else f"'{part}'")
        elif col == "timestamp" and table in ("requests", "transactions", "notifications"):
            values.append(f"'{part}'::timestamp")
        elif col == "encrypted_password":
            values.append(f"'{part.replace(chr(39), chr(39)*2)}'")
        elif col in ("is_super_admin", "is_sso_user", "deleted_at", "is_anonymous"):
            if part == r"\N":
                values.append("NULL")
            elif part == "t":
                values.append("true")
            elif part == "f":
                values.append("false")
            else:
                values.append(part)
        elif col == "email_change_confirm_status":
            values.append(part)
        else:
            values.append(pg_copy_field_to_sql(part, col))
    col_list = ", ".join(f'"{c}"' if c == "timestamp" else c for c in cols)
    return f"INSERT INTO {schema}.{table} ({col_list}) VALUES ({', '.join(values)}) ON CONFLICT DO NOTHING;"


schema_sql = """
-- Kelimkar schema restore
CREATE TABLE IF NOT EXISTS public.notifications (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stankar text NOT NULL,
    message text DEFAULT 'Potřebujeme kelímky!'::text,
    status text DEFAULT '"na cestě", "hotovo"'::text,
    "timestamp" timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY,
    role text NOT NULL,
    name text
);

CREATE TABLE IF NOT EXISTS public.requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stankar text NOT NULL,
    "timestamp" timestamp without time zone DEFAULT now(),
    status text DEFAULT 'čeká'::text
);

CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zamestnanec text DEFAULT '-'::text NOT NULL,
    male_kelimky smallint DEFAULT 0,
    velke_kelimky smallint DEFAULT 0,
    "timestamp" timestamp without time zone DEFAULT (now() AT TIME ZONE 'Europe/Prague'::text),
    status text DEFAULT '''ceka'', ''potvrzeno'''::text,
    stankar text,
    typ_vymeny text DEFAULT 'O+V'::text
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS allow_all ON public.transactions;
CREATE POLICY allow_all ON public.transactions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS allow_insert_requests ON public.requests;
CREATE POLICY allow_insert_requests ON public.requests FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS allow_select_profiles ON public.profiles;
CREATE POLICY allow_select_profiles ON public.profiles FOR SELECT USING (true);

GRANT ALL ON TABLE public.notifications TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.profiles TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.requests TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.transactions TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
"""

lines = [schema_sql.strip(), ""]

# Auth users - simplified insert with key columns only from backup
auth_user_cols = [
    "instance_id", "id", "aud", "role", "email", "encrypted_password",
    "email_confirmed_at", "raw_app_meta_data", "raw_user_meta_data",
    "created_at", "updated_at", "email_change_confirm_status", "is_sso_user", "is_anonymous"
]
cols, rows = extract_copy("auth", "users")
lines.append("-- auth.users")
for row in rows:
    full_cols, full_row = cols, row
    # use full insert from backup columns
    lines.append(copy_row_to_insert("auth", "users", full_cols, row))

lines.append("")
cols, rows = extract_copy("auth", "identities")
lines.append("-- auth.identities")
for row in rows:
    lines.append(copy_row_to_insert("auth", "identities", cols, row))

lines.append("")
for table in ["profiles", "requests", "transactions"]:
    cols, rows = extract_copy("public", table)
    lines.append(f"-- public.{table}")
    for row in rows:
        lines.append(copy_row_to_insert("public", table, cols, row))
    lines.append("")

lines.append("SELECT setval('public.requests_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.requests));")
lines.append("SELECT setval('public.transactions_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.transactions));")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT} ({len(lines)} statements)")
